defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: shopify_mobile_development

test:
  <<: *defaults
  database: shopify_mobile_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: shopify_mobile
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
